server:
  port: 8888  # 项目的端口号，默认端口号8080，范围1-65535
  servlet:
    context-path: /kunpu   # 上下文路径，所有请求路径前面必须添加此路径
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kunpu
    username: root
    password: 18200358320Storm
    druid:
      initial-size: 5 # 初始化连接数
      max-active: 30  # 最大连接数
      min-idle: 3     # 最小空闲数
      max-wait: 4000  # 超时时间，单位：毫秒
mybatis:
  type-aliases-package: com.sx.sports.entity
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true